* Rahil Sayyad
* rahilsayyad389@gmail.com

## Zoo Dataset_Classification


In [1]:
## import libraries
import pandas as pd 
import numpy as np

In [2]:
# read dataset
df=pd.read_csv("Zoo.csv")

In [3]:
df

animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  type  
0          1     1  
1          1     1  
2          0     4  
3          1     1  
4          1     1  
..       ...   ...  
96         1     1  
97         0     6  
98         1     1  
99         0     7  
100        0     2  

[101 rows x 18 columns]

In [4]:
df["type"].unique()

array([1, 4, 2, 7, 6, 5, 3], dtype=int64)

In [82]:
# find null value
df.isna().sum()


animal name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
type           0
dtype: int64

In [83]:
df["animal name"].unique()

array(['aardvark', 'antelope', 'bass', 'bear', 'boar', 'buffalo', 'calf',
       'carp', 'catfish', 'cavy', 'cheetah', 'chicken', 'chub', 'clam',
       'crab', 'crayfish', 'crow', 'deer', 'dogfish', 'dolphin', 'dove',
       'duck', 'elephant', 'flamingo', 'flea', 'frog', 'fruitbat',
       'giraffe', 'girl', 'gnat', 'goat', 'gorilla', 'gull', 'haddock',
       'hamster', 'hare', 'hawk', 'herring', 'honeybee', 'housefly',
       'kiwi', 'ladybird', 'lark', 'leopard', 'lion', 'lobster', 'lynx',
       'mink', 'mole', 'mongoose', 'moth', 'newt', 'octopus', 'opossum',
       'oryx', 'ostrich', 'parakeet', 'penguin', 'pheasant', 'pike',
       'piranha', 'pitviper', 'platypus', 'polecat', 'pony', 'porpoise',
       'puma', 'pussycat', 'raccoon', 'reindeer', 'rhea', 'scorpion',
       'seahorse', 'seal', 'sealion', 'seasnake', 'seawasp', 'skimmer',
       'skua', 'slowworm', 'slug', 'sole', 'sparrow', 'squirrel',
       'starfish', 'stingray', 'swan', 'termite', 'toad', 'tortoise',
       

In [84]:
df["animal name"].value_counts()

frog        2
pony        1
sealion     1
seal        1
seahorse    1
           ..
gorilla     1
goat        1
gnat        1
girl        1
wren        1
Name: animal name, Length: 100, dtype: int64

## separate x independant and y dependant variable

In [87]:
features = list(df.columns.values)
features.remove('legs')
features.remove('type')
features.remove('animal name')
features

['hair',
 'feathers',
 'eggs',
 'milk',
 'airborne',
 'aquatic',
 'predator',
 'toothed',
 'backbone',
 'breathes',
 'venomous',
 'fins',
 'tail',
 'domestic',
 'catsize']

In [88]:
x=df[features]

In [89]:
x

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  tail  domestic  catsize  
0           1         1         0     0     0         0        1  
1           1         1         0     0     1         0        1  
2           1         0         0     1     1         0        0  
3           1         1         0     0     0         0        1  
4           1         1         0     0     1         0        1  
..        ...       ...       ...   ...   ...       ...      ...  
96          1         1         0     0     1         0        1  
97          0         1         1     0     0         0        0  
98          1         1         0     0     1         0        1  
99          0         1         0     0     0         0        0  
100         1         1         0     0     1         0        0  

[101 rows x 15 columns]

In [91]:
y = df['type']

In [92]:
y.head(4)

0    1
1    1
2    4
3    1
Name: type, dtype: int64

# split the data in train and test side

In [93]:
from sklearn.model_selection import train_test_split

In [118]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

## fitting the knn model

In [119]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(5)
knn

KNeighborsClassifier()

In [120]:
# fit the model on training data
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [121]:
y_pred=knn.predict(x_test)

In [122]:
y_pred

array([5, 4, 4, 1, 1, 1, 2, 4, 1, 1, 7, 1, 2, 7, 4, 6, 1, 6, 2, 4, 2, 3,
       1, 2, 1, 1], dtype=int64)

In [123]:
y_test

26    5
86    4
2     4
55    1
75    1
94    1
16    2
73    4
54    1
96    1
53    7
93    1
78    2
13    7
7     4
30    6
22    1
24    6
33    2
8     4
43    2
62    3
3     1
71    2
45    1
48    1
Name: type, dtype: int64

In [124]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred,y_test))
accuracy_score(y_pred,y_test)

[[10  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]


1.0

In [125]:
from sklearn.metrics import r2_score

In [127]:
r2_score(y_pred,y_test)

1.0