In [70]:
# importing libraries
import numpy as np
import pandas as pd

In [71]:
#read dataset
df=pd.read_csv("delivery_time.csv")

In [72]:
df

Delivery Time  Sorting Time
0           21.00            10
1           13.50             4
2           19.75             6
3           24.00             9
4           29.00            10
5           15.35             6
6           19.00             7
7            9.50             3
8           17.90            10
9           18.75             9
10          19.83             8
11          10.75             4
12          16.68             7
13          11.50             3
14          12.03             3
15          14.88             4
16          13.75             6
17          18.11             7
18           8.00             2
19          17.83             7
20          21.50             5

In [73]:
#check null values
df.isnull().sum()

Delivery Time    0
Sorting Time     0
dtype: int64

In [74]:
# separate x and y variable
x=df["Sorting Time"]

In [75]:
x

0     10
1      4
2      6
3      9
4     10
5      6
6      7
7      3
8     10
9      9
10     8
11     4
12     7
13     3
14     3
15     4
16     6
17     7
18     2
19     7
20     5
Name: Sorting Time, dtype: int64

In [76]:
y=df["Delivery Time"]

In [104]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=22)

In [105]:
# fitting the model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [106]:
x_train=x_train.values.reshape(-1,1)
y_train=y_train.values.reshape(-1,1)
y_test=y_test.values.reshape(-1,1)
x_test=x_test.values.reshape(-1,1)

In [107]:
# fit the data for traning
lr.fit(x_train,y_train)

LinearRegression()

In [108]:
x_test


array([[9],
       [9],
       [3],
       [4],
       [6],
       [2],
       [4]], dtype=int64)

In [109]:
y_pred=lr.predict(x_test)

In [110]:
y_pred

array([[21.39925854],
       [21.39925854],
       [11.67387317],
       [13.29477073],
       [16.53656585],
       [10.05297561],
       [13.29477073]])

In [111]:
y_test

array([[24.  ],
       [18.75],
       [12.03],
       [14.88],
       [15.35],
       [ 8.  ],
       [13.5 ]])

In [112]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.8227505116195706

In [69]:
## save the model on disk
import pickle
filename="delivery_time.pkl"
pickle.dump(lr,open(filename,'wb'))